### ISSUE TITLE
Cannot build in raspberry pi 2 with node 0.12

### ISSUE THREAD

**Issue by andrea-spotsoftware** [egorFiNE/node-reboot#1]
I have this error when trying to install the module:

```
 reboot@0.0.1 install /home/pi/io-at-spot/io-at-spot/node_modules/reboot
> node-gyp rebuild

make: Entering directory '/home/pi/io-at-spot/io-at-spot/node_modules/reboot/build'
  CXX(target) Release/obj.target/reboot_bindings/src/reboot.o
../src/reboot.cc:12:40: error: 'Arguments' does not name a type
../src/reboot.cc:12:51: error: ISO C++ forbids declaration of 'args' with no type [-fpermissive]
../src/reboot.cc: In function 'v8::Handle<v8::Value> _rebootImmediately(const int&)':
../src/reboot.cc:19:19: error: too few arguments to function 'v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)'
/root/.node-gyp/0.12.6/deps/v8/include/v8.h:305:28: note: declared here
../src/reboot.cc: At global scope:
../src/reboot.cc:22:29: error: 'Arguments' does not name a type
../src/reboot.cc:22:40: error: ISO C++ forbids declaration of 'args' with no type [-fpermissive]
../src/reboot.cc: In function 'v8::Handle<v8::Value> _reboot(const int&)':
../src/reboot.cc:31:19: error: too few arguments to function 'v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)'
/root/.node-gyp/0.12.6/deps/v8/include/v8.h:305:28: note: declared here
../src/reboot.cc: In function 'void init(v8::Handle<v8::Object>)':
../src/reboot.cc:36:43: error: no matching function for call to 'NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [7], v8::Handle<v8::Value> (&)(const int&))'
../src/reboot.cc:36:43: note: candidate is:
/root/.node-gyp/0.12.6/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
../src/reboot.cc:37:65: error: no matching function for call to 'NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [18], v8::Handle<v8::Value> (&)(const int&))'
../src/reboot.cc:37:65: note: candidate is:
/root/.node-gyp/0.12.6/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
../src/reboot.cc: In function 'v8::Handle<v8::Value> _reboot(const int&)':
../src/reboot.cc:32:1: warning: control reaches end of non-void function [-Wreturn-type]
../src/reboot.cc: In function 'v8::Handle<v8::Value> _rebootImmediately(const int&)':
../src/reboot.cc:20:1: warning: control reaches end of non-void function [-Wreturn-type]
reboot_bindings.target.mk:83: recipe for target 'Release/obj.target/reboot_bindings/src/reboot.o' failed
make: *** [Release/obj.target/reboot_bindings/src/reboot.o] Error 1
make: Leaving directory '/home/pi/io-at-spot/io-at-spot/node_modules/reboot/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.18.11-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/io-at-spot/io-at-spot/node_modules/reboot
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.18.11-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "reboot"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! reboot@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reboot@0.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the reboot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls reboot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/io-at-spot/io-at-spot/npm-debug.log
```

**Comment by egorFiNE** [comment]
it's been two years since I have last updated this module. In theory it is going to be easy; however I'm not sure I can find time soon enough for it. :)

**Comment by egorFiNE** [comment]
Module updated, now builds with node 10.x.
